pub const CHECK_MARK: &str = "✔";
pub const CROSS_MARK: &str = "✕";
pub const COMPLETED: &str = "[x]";
pub const NOT_COMPLETED: &str = "[ ]";
pub const COMPLETED_CIRCLE: &str = "●";
pub const NOT_COMPLETED_CIRCLE: &str = "○";
pub const EDIT_ICON: &str = "✎";
pub const DELETE_ICON: &str = "🗑";
pub const ELLIPSIS: &str = "…";
